# Build settings
markdown: kramdown

# Site settings
title: "JekyllMDL"
description: "MDL Based Jekyll Theme"
email: sukso96100@gmail.com

name: 'Youngbin Han'
author: 'Youngbin Han'

paginate:	5

#url: "http://indeex.org" # the base hostname & protocol for your site
url: "/jekyll-theme-mdl"
baseurl: ""

#Your Disqus Shortname
disqus_shortname: disqus
